### ISSUE TITLE
Segmentation faults when compiled with cmake

### ISSUE THREAD

**Issue by mbkumar** [PrincetonUniversity/SPEC#146]
I am building SPEC with cmake (in the cmake branch I am working on), instead of the supplied Makefile. The code is compiling fine and xspec executable is generated. When running the test in ci/G1V03L2Fi, I am getting segmentation faults. To my understanding I am using all the flags specified in the Makefile in the cmake setup as well, so not sure what is causing the issue.

I am running the following command:
```bash
mpiexec -n 1 valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ${SPEC_PATH}/xspec G1V03L2Fi.001.sp
```
I am attaching the [valgrind output](https://github.com/PrincetonUniversity/SPEC/files/6511021/valgrind_log.txt). If anyone knows the fix, please let me know.

**Comment by zhucaoxiang** [comment]
@mbkumar I don't want to create a new issue. I think this is relevant.
I got the following error when compiling on stellar. Do you know if the dependence of CMAKE>3.20 can be revised? Somehow, stellar only has 3.18 and 3.19.
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.20.0 or higher is required.  You are running version 3.18.2
```

**Comment by mbkumar** [comment]
Easiest would be to use a conda virtual environment and do "pip install
cmake".
Could you please modify the SPEC/CMakeLists.txt line-1 and downgrade to
3.18.0 and check if it is working? If it is, you/I can issue a patch.

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by zhucaoxiang** [comment]
@mbkumar After changing the CMakeLists.txt, I got the following error. Any clue?
```
$ cmake -DCMAKE_Fortran_COMPILER=/opt/intel/oneapi/mpi/2021.1.1/bin/mpiifort .
-- The C compiler identification is unknown
-- The Fortran compiler identification is Intel 20.2.1.20201208
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/mpi/2021.1.1/bin/mpicc - skipped
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/intel/oneapi/mpi/2021.1.1/bin/mpiifort - skipped
-- Checking whether /opt/intel/oneapi/mpi/2021.1.1/bin/mpiifort supports Fortran 90
-- Checking whether /opt/intel/oneapi/mpi/2021.1.1/bin/mpiifort supports Fortran 90 - yes
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Found OpenMP_Fortran: -qopenmp (found version "5.0")
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND) (found version "5.0")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Could NOT find Threads (missing: Threads_FOUND)
-- Looking for pow in m
-- Looking for pow in m - not found
-- compiler is mpiifort
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindThreads.cmake:234 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/share/cmake/Modules/FindBLAS.cmake:310 (find_package)
  CMakeLists.txt:63 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by mbkumar** [comment]
Hello Caoxiang,

The best approach is to create a build folder and change to that and then
run *cmake <cmake_flags> ..*
Example cmake flags could be found cmake_machines/*.json files. I'll add
more machines in the future.



Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by mbkumar** [comment]
The issue is now fixed thanks to the help from Kitware.
