### ISSUE TITLE
Help needed to install python wrappers

### ISSUE THREAD

**Issue by abaillod** [PrincetonUniversity/SPEC#151]
Hello everyone!

_I am not sure where to post this question - there is both a Slack and a Github for both SIMSOPT and SPEC... I try it here, if it is better to move it elsewhere, please tell me and I will move it!_

I am trying to install the latest version of SIMSOPT and do some basic optimization with some SPEC equilibria. However I am running into troubles when trying to install the python wrappers. Could someone please help me? What I did for now is:

```
(simsopt) abaillod@spcpc602:~/simsopt> git pull origin master
From github.com:hiddenSymmetries/simsopt
 * branch            master     -> FETCH_HEAD
Already up to date.
(simsopt) abaillod@spcpc602:~/simsopt> pip install -e .[SPEC]
... (lots of outputs)
Installing collected packages: simsopt
  Running setup.py develop for simsopt
Successfully installed simsopt-0.4.7.dev3+g2a8de1b
```

Then I tried to create a SPEC object:

```
>>> import numpy as np
>>> from simsopt.mhd.spec import Spec
>>> import py_spec

>>> s = Spec('Input_000.sp')

RuntimeError: Using Spec requires spec python wrapper to be installed.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-fd09613c24d6> in <module>
      5 import py_spec
      6 
----> 7 s = Spec('Input_000.sp')

~/simsopt/src/simsopt/util/dev.py in decorated(*args, **kwargs)
     19             if not self.condition:
     20                 raise RuntimeError(self.message)
---> 21             return _callable(*args, **kwargs)
     22 
     23         return decorated

~/simsopt/src/simsopt/mhd/spec.py in __init__(self, filename, mpi, verbose, keep_all_files)
     98         if spec is None:
     99             raise RuntimeError(
--> 100                 "Using Spec requires spec python wrapper to be installed.")
    101 
    102         #if not py_spec_found:

RuntimeError: Using Spec requires spec python wrapper to be installed.
```

I tried to install the python wrapper following the documentation in SPEC, i.e.:

```
(simsopt) abaillod@spcpc602:~/SPEC/Utilities/python_wrapper> pip install -U git+https://github.com/zhucaoxiang/f90wrap
... (some outputs)
Successfully installed f90wrap-0.2.3
(simsopt) abaillod@spcpc602:~/SPEC/Utilities/python_wrapper> make BUILD_ENV=intel_spc all
mpif90 -E -x f95-cpp-input -fPIC ../..//inputlist_m.F90  -o inputlist.fpp
ifort: command line warning #10155: ignoring option '-x'; argument required
ifort: error #10236: File not found:  'f95-cpp-input'
# 1 "../..//inputlist_m.F90"
... (long output)
make: *** [Makefile:107: inputlist.fpp] Error 1
```

Any idea what is wrong? Is it because I am using an intel compiler?

Thanks!

**Comment by abaillod** [comment]
Hello again,

I reopen this issue because, even though I followed every tips we discussed above, I can't recompile the python wrappers for some reasons. I am using the latest master commit, `dec8eb7`, and I modified the Makefile in `./Utilities/python_wrapper` as in my previous message.

I also created a new virtual environment, with `mkvirtualenv test --no-site-packages` and I installed the latest versions of numpy, and all requirements in `./Utilities/pythontools` using `pip`.

Now, when running the python wrapper Makefile, I get lots of output and, at the end

```
(test) abaillod@spcpc602:~/SPEC/Utilities/python_wrapper> make BUILD_ENV=intel_spc all
...
Found executable /usr/local/intel/19.1/compilers_and_libraries_2019.1.144/linux/bin/intel64/ifort
customize LaheyFCompiler
Could not locate executable lf95
lahey: no Fortran 77 compiler found
lahey: no Fortran 77 compiler found
customize PGroupFCompiler
Could not locate executable pgfortran
pg: no Fortran 77 compiler found
pg: no Fortran 77 compiler found
customize NVHPCFCompiler
Could not locate executable nvfortran
nv: no Fortran 77 compiler found
nv: no Fortran 77 compiler found
customize AbsoftFCompiler
Could not locate executable f77
absoft: no Fortran 77 compiler found
absoft: no Fortran 77 compiler found
customize NAGFCompiler
Could not locate executable f95
nag: no Fortran 77 compiler found
nag: no Fortran 77 compiler found
customize VastFCompiler
customize CompaqFCompiler
Could not locate executable fort
compaq: no Fortran 77 compiler found
compaq: no Fortran 77 compiler found
...
...
...
In file included from /home/abaillod/.virtualenvs/simsopt/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /home/abaillod/.virtualenvs/simsopt/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/abaillod/.virtualenvs/simsopt/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from ./src.linux-x86_64-3.6/./src.linux-x86_64-3.6/fortranobject.h:13,
                 from ./src.linux-x86_64-3.6/./src.linux-x86_64-3.6/fortranobject.c:2:
/home/abaillod/.virtualenvs/simsopt/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
...
...
...
/usr/local/intel/19.1/compilers_and_libraries_2019.1.144/linux/mpi/intel64/bin/mpif90 -shared -shared -nofor_main ./src.linux-x86_64-3.6/_specmodule.o ./src.linux-x86_64-3.6/src.linux-x86_64-3.6/fortranobject.o ./f90wrap_global.o ./f90wrap_inputlist.o ./f90wrap_intghs.o ./f90wrap_newton.o ./f90wrap_sphdf5.o ./f90wrap_toplevel.o -L. -L/usr/local/intel/19.1/compilers_and_libraries_2019.1.144/linux/mkl/lib/intel64 -L/usr/local/hdf5-1.8.21-intel19.1/lib -L/usr/local/fftw3/lib -L/usr/lib64 -lspec -lmkl_rt -lpthread -lm -ldl -lhdf5_fortran -lhdf5 -lpthread -lz -lm -lfftw3 -liomp5 -lpython3.6m -o ./_spec.cpython-36m-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'spec' has no attribute 'constants'
make: *** [Makefile:137: test] Error 1
```

It seems I have two separated issues; (1) apparently my FORTRAN 77 compiler can't be found and (2) I get some warnings about the Numpy version I using, even though I am using the latest one... Any idea what is wrong?

**Comment by zhucaoxiang** [comment]
@abaillod Are you able to compile SPEC standalone? Is there the same error message?

**Comment by abaillod** [comment]
Yes, I can compile SPEC without problem.

**Comment by zhucaoxiang** [comment]
What about `make all_clean` first and then `make BUILD_ENV=intel_spc al`?

**Comment by abaillod** [comment]
Yes, sorry I forgot to mention it but I did `make all_clean` before trying to compile.

I tried to compile older version of SPEC and the python wrappers. 

1.  Commit 6e22d4b07ac9faf05478d98c5b80ff7bed138a30 (10 Jun 2021): This is, if I am not wrong, the commit I was using when I opened this issue. With the Makefile fix, it was working. I tried again to see if the error is coming from my side, and I get the same warnings about numpy, the same error message about the fortran 77 compiler not found, BUT the compilation goes on and finishes without error!

2. Release 3.11 (931698d): I get the same error messages, and the compilation crashes with `make: *** [Makefile:137: test] Error 1`.

Conclusion: something was introduced between commit 6e22d4b07ac9faf05478d98c5b80ff7bed138a30 and 931698d that broke the python wrapper compilation on my machine. What is this `Makefile:137: test` thing? Is there a test that has been added to the compilation?

**Comment by zhucaoxiang** [comment]
This is strange. If you look at the current version (v3.11), `Makefile` was last modified 8 months ago and `test` is in line 131, not 137. https://github.com/PrincetonUniversity/SPEC/blob/master/Utilities/python_wrapper/Makefile#L131

I guess you have modified the Makefile?

**Comment by abaillod** [comment]
Caoxiang and I had a quick zoom to solve the problem, here is a summary for reference:

The problem arise when attempting to import the spec wrappers in python once the compilation is done. There is a name conflict between the python wrapper library, named `spec`:

```
_spec.cpython-36m-x86_64-linux-gnu.so
spec.py
```

and the directory `SPEC/Utilities/python_wrapper/spec`. When doing `import spec` from within python, python gets confused and imports the directory, which of course does not work...

A quick, but temporary fix is to rename the python wrappers library. The line `PYTHON_MODN = spec` has to be changed to any other name, for example `PYTHON_MODN = spec_wrapper`. Then, `import spec_wrapper` works; this requires however to change the imports in all other codes, such as simsopt.

Maybe the better solution would be to rename the directory `SPEC/Utilities/python_wrapper/spec`. I am not sure what is this directory doing and where changes are required though...

**Comment by jonathanschilling** [comment]
@abaillod @zhucaoxiang  Good find!
A quick fix is to move the output of `f90wap` (namely `_spec.cpython-36m-x86_64-linux-gnu.so` and `spec.py` into the `SPEC/Utilities/python_wrapper/spec` directory.

In the `spec` directory is a file ` core.py`.  
This contains a wrapper around the auto-generated `spec.py` and `_spec....so` for convenience.  
I guess this is also what is actually imported by SIMSOPT.

As a fix, I support suggest to rename the auto-generated module to `spec_wrapper` (maybe re-named to `spec_f90wrapped`?).
The `Makefile` for the `python_wrapper` should then be adjusted to move the auto-generated `_spec_f90wrapped.cpython-36m-x86_64-linux-gnu.so` and `spec_f90wrapped.py` into the `SPEC/Utilities/python_wrapper/spec` directory.

**Comment by abaillod** [comment]
This has been solved thanks to the recent fixes. I am closing it!
