### ISSUE TITLE
Problem running tests on master branch

### ISSUE THREAD

**Issue by richardnies** [PrincetonUniversity/SPEC#156]
In the master branch, some of the tests in `InputFiles/TestCases `seem to be failing (e.g. `G3V02L1Fi.001.sp`) with `volume :      fatal : myid=  0 ; vflag.eq.0 .and. vvolume(lvol).lt.small ; volume cannot be zero or negative ;`.

This problem was also encountered by @jloizu ?

For some reason, the tests run fine in `ci`?

**Comment by jonathanschilling** [comment]
`pywrap_makefile` is merged into `master` now. Please re-open if this issue is still present.
