### ISSUE TITLE
MATLAB metric subroutine needs fix

### ISSUE THREAD

**Issue by zhisong** [PrincetonUniversity/SPEC#166]
The MATLAB subroutine get_spec_metric is not giving correct answers for the innermost volume. Most likely it is because there is a problem with get_spec_regularization_factor. In the new version of SPEC (>3.0) the regularization factors for coordinate interpolation have been changed. But this is not reflected in the MATLAB subroutines.

**Comment by abaillod** [comment]
Hi Zhisong,

True, the matlab tools on the master branch are very outdated (~2 years old). I pushed my updated routines to the branch `matlab_update` - you can try with these one.

I never found the time to properly test all these routines, so I never merged the branch with the master one...

**Comment by smiet** [comment]
Fixed with PR #169 . Closing
