### ISSUE TITLE
Python wrapper compilation for Henneberg representation branch

### ISSUE THREAD

**Issue by abaillod** [PrincetonUniversity/SPEC#167]
Hello,

I finally debugged the Henneberg representation (See branch HennebergRepresentation) and I would like to compile its fortran wrappers. I followed the steps listed in ./Compile.md but I get an error. Note that the compilation of the python wrappers for the master branch work well using this approach, so I don't think the problem is related to my environment.

After running `python setup.py bdist_wheel`, I got lots of output and then it crashes at the step 197/200:
```
... 
[197/200] Linking Fortran executable build/bin/xspec
FAILED: build/bin/xspec 
: && /misc/Anaconda3/envs/spec_env/bin/mpif90 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/misc/Anaconda3/envs/spec_env/lib -Wl,-rpath-link,/misc/Anaconda3/envs/spec_env/lib -L/misc/Anaconda3/envs/spec_env/lib -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /misc/Anaconda3/envs/spec_env/include  -O3 -DNDEBUG -O3 src/CMakeFiles/xspec.dir/mxspech_m.F90.o -o build/bin/xspec  build/lib/libspec.a  /misc/Anaconda3/envs/spec_env/lib/libhdf5_fortran.so  /misc/Anaconda3/envs/spec_env/lib/libhdf5.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3f.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3l.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3_threads.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3f_threads.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3l_threads.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3_omp.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3f_omp.so  /misc/Anaconda3/envs/spec_env/lib/libfftw3l_omp.so  /misc/Anaconda3/envs/spec_env/lib/libopenblas.so && :
/misc/Anaconda3/envs/spec_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: src/CMakeFiles/xspec.dir/mxspech_m.F90.o: in function `spec_':
mxspech_m.F90:(.text.spec_+0x27b0): undefined reference to `wrtend_'
/misc/Anaconda3/envs/spec_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: src/CMakeFiles/xspec.dir/mxspech_m.F90.o: in function `xspech_':
mxspech_m.F90:(.text.xspech_+0x7ae): undefined reference to `wrtend_'
/misc/Anaconda3/envs/spec_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: mxspech_m.F90:(.text.xspech_+0x7bb): undefined reference to `wrtend_'
/misc/Anaconda3/envs/spec_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: build/lib/libspec.a(newton_m.F90.o): in function `fcn1_':
newton_m.F90:(.text.fcn1_+0xe9b): undefined reference to `wrtend_'
/misc/Anaconda3/envs/spec_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: build/lib/libspec.a(newton_m.F90.o): in function `fcn2_':
newton_m.F90:(.text.fcn2_+0x1189): undefined reference to `wrtend_'
collect2: error: ld returned 1 exit status
```

Could someone help me with that? I would be interested to see if you face the same issue on your local machines. Thanks!

Edit: it seems that the compilation of the python wrappers also crashes on the ci tests.

(Note that I also tried to compile by using the Makefile in `Utilities/python_wrapper/.` but then I get a bunch of errors, that I think are related to how my environment is set up. I think it is easier to make the cmake compilation work...)

**Comment by smiet** [comment]
Hi @abaillod, is this still relevant? 

The error is thrown in the compilation of the Fortran code, not in the wrapping step. 

- can you check if you can build the code itself using `CMake`? (in `SPEC_ROOT` do `mkdir build && cd build && cmake .. && make -j 4`)

- try compiling straight from the Makefile, remembering to set your BUILD_ENV (`BUILD_ENV=gfortran[_debian,_arc,...] make` )

Hope this helps.

**Comment by abaillod** [comment]
Hi Chris - this is an old branch, I think we can forget about it. I am happy if someone else wants to take over and complete the merge if there is any use to it!

I am closing the issue for now. Thank you for following up anyway!
