### ISSUE TITLE
404 URLs in README 

### ISSUE THREAD

**Issue by missing-user** [PrincetonUniversity/SPEC#205]
Sometime over the last few months the links referenced in the README have gone stale, specifically the ones under the user directory of https://w3.pppl.gov/~shudson

Since these URLs are also being referenced by other documentations (e.g. simsopt) it might be good to setup redirects  @SRHudson 

Impacted URLs:
- https://w3.pppl.gov/~shudson/Spec/spec.html
- https://w3.pppl.gov/~shudson/Spec/SpecFlowchart.pdf
Also this URL from another issue thread
- https://w3.pppl.gov/~shudson/Spec/ma00aa.pdf

**Comment by jonathanschilling** [comment]
Maybe we should just remove those links in the doxygen parts of the codebase and replace them with info that is put in their place directly in doxygen?

**Comment by missing-user** [comment]
Sure,  I was able to recover these files from the InternetArchive, and would just put them directly in the repo for now.
[SpecFlowchart.pdf](https://github.com/user-attachments/files/17758941/SpecFlowchart.pdf)
[SpecPreset.pdf](https://github.com/user-attachments/files/17758942/SpecPreset.pdf)

https://w3.pppl.gov/~shudson/Spec/spec.html used to host a list of SPEC related publications, not sure how we can replace that...

**Comment by jloizu** [comment]
Hello, nice to see so much activity on SPEC development! :)

About the publications, it would be good if we simply add a list on the SPEC github repo with all SPEC-related publications (we can put the main ones, and then people can add any additional paper they did using SPEC?)

**Comment by jons-pf** [comment]
@jloizu Regarding publications, we have this page which could be extended: https://princetonuniversity.github.io/SPEC/citelist.html
and also a ready-to-use BibTex file: https://github.com/PrincetonUniversity/SPEC/blob/master/spec_refs.bib 
Both are absolutely not up-to-date.

We might also want to consider a `CITATION.cff` file for SPEC: https://citation-file-format.github.io/

**Comment by missing-user** [comment]
Ok, so a couple things came up that may require discussion:
- As authors of the SPEC _software_ I listed Hudson and the top 10 contributors in order
- But I'm assuming the preferred citation format should be the _paper_ https://doi.org/10.1063/1.4765691 
- The references were mostly adapted from the bibtex file + free boundary SPEC paper, I only added the verification and free boundary papers, which were missing: https://doi.org/10.1088/1361-6587/ab7fc5 and https://dx.doi.org/10.1088/1361-6587/ab9a61 

https://github.com/missing-user/SPEC/blob/readme-404-fix/CITATION.cff

**Comment by jloizu** [comment]
Thanks! Can you add also these papers? in fact some of these are the closest to 'code verification' papers:
- https://doi.org/10.1063/1.4967709
- https://doi.org/10.1017/S0022377821000520
- https://doi.org/10.1063/1.4944818
- https://doi.org/10.1063/1.4931094
- https://doi.org/10.1063/1.4906888
- https://doi.org/10.1063/5.0009110
- https://doi.org/10.1017/S0022377823000934
- https://doi.org/10.1017/S0022377817000861
- https://doi.org/10.1017/S0022377823000910
- https://doi.org/10.1063/1.5091765

**Comment by zhucaoxiang** [comment]
We also have a recent publication using SPEC doing some work. Might be relevant. https://dx.doi.org/10.1088/1741-4326/ad39d9

**Comment by jloizu** [comment]
I think it would have all these publications that used SPEC in the section:
"A list of publications using SPEC are in our [bibliography section](https://princetonuniversity.github.io/SPEC/citelist)"
and the 'citation list' for the SPEC code should only contain the two main SPEC papers? (namely the original 2012 and the free-boundary extension 2020)
